### ISSUE TITLE
calling batti in backend!

### ISSUE THREAD

**Issue by rhoit** [samundra/Nepal-Loadshedding-Indicater#2]
```bash
$ batti -g<group_no> -t #will give you current schedule
```

which can be call the batti using python submodule, so that you don't need to maintain the `routine.xml` and use the batti's `~/.cache/batti.sch`

```python
from subprocess import check_output

batti="path/to/batti"
print(check_output([batti, "-g3", "-t"], universal_newlines=True).split())
```

**Comment by samundra** [comment]
Closing the issue. As this project has been discontinued.
